{% set name = "playwright-stealth" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/playwright-stealth-{{ version }}.tar.gz
  sha256: b504d951d00fac755c7d13665a29611d415180510bd7d23f14ebc89439ba2043

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - setuptools
    - playwright-python

test:
  imports:
    - playwright_stealth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AtuboDad/playwright_stealth
  summary: playwright stealth
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
